---
domain: conectado.local
cluster_name: BlackTeam001
ELASTIC_MASTER: "172.2.31.9"
ELASTIC_SLAVE:  "172.2.31.78"

users:
  - { user: admin, password: 1q2w3e }
  - { user: lauro, password: 1q2w3e }


