---

- name: Restart auditbeat
  ansible.builtin.service:
    name: auditbeat
    state: restarted
    enabled: yes

- name: Restart filebeat
  ansible.builtin.service:
    name: filebeat
    state: restarted
    enabled: yes

- name: Restart metricbeat
  ansible.builtin.service:
    name: metricbeat
    state: restarted
    enabled: yes

