metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
setup.kibana:
output.elasticsearch:
  hosts: ["{{ELASTIC_MASTER}}:9200"]
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
