---

- name: Stopping elasticsearch
  shell: systemctl stop elasticsearch.service

- name: Install metrics
  shell: yum install -y metricbeat

- name: Start metrics
  shell: systemctl start metricbeat

- name: Active monitoring elastic
  shell: metricbeat modules enable elasticsearch-xpack

- name: Start and enable metrics
  shell: systemctl restart metricbeat && systemctl enable metricbeat

- name: Starting elasticsearch
  shell: systemctl restart elasticsearch.service
